apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: judicial-life-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: homepage.judicial.life
      service: http://homepage-service.homepage.svc.cluster.local:3000
    - hostname: openwebui.judicial.life
      service: http://openwebui-service.openwebui.svc.cluster.local:8080
    - hostname: ollama.judicial.life
      service: http://ollama-service.openwebui.svc.cluster.local:11434
    - hostname: paperless.judicial.life
      service: http://paperless-ngx-service.paperless-ngx.svc.cluster.local:8000
    - hostname: argocd.judicial.life
      service: http://argocd-server.argocd.svc.cluster.local:80
    - service: http_status:404
